FROM quay.io/rdacosta/my_httpd:broken

RUN sed -i -e 's/^Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd/ /var/run/httpd/ && \
    chmod -R g=u /var/log/httpd/ /var/run/httpd/
